default:
  image: condaforge/linux-anvil-cos7-x86_64:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .conda_packages

# === Variables ===

variables:
  PACKAGE_VERSION: 0.1.3

.configure:
  before_script:
    # Cargo
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh 2>/dev/null
    # Conda environment variables
    - export CONDA_PKGS_DIRS="${CI_PROJECT_DIR}/.conda_packages"
    # Make conda cache and bld folders
    - mkdir -p "${CI_PROJECT_DIR}/conda-bld" "${CONDA_PKGS_DIRS}"
    # Conda configure
    - conda config --append channels ostrokach-forge
    - conda config --append channels conda-forge
    - conda update -yq conda

# === Build ===

build:
  stage: build
  extends:
    - .configure
  script:
    - cd "${CI_PROJECT_DIR}/.conda"
    - conda build .
      --no-test
      --output-folder "${CI_PROJECT_DIR}/conda-bld"
  artifacts:
    paths:
      - conda-bld

# === Test ===

test:
  stage: test
  extends:
    - .configure
  dependencies:
    - build
  script:
    # Restore built packages
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    # Run tests
    - cd $CI_PROJECT_DIR/.conda
    - conda build .
      --test

# === Pages ===

pages:
  stage: test
  extends:
    - .configure
  dependencies:
    - build
  script:
    # Conda install
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    - conda install -yq --use-local "python=$PYTHON_VERSION" $CI_PROJECT_NAME
    # Build docs
    - conda install -yq nbconvert ipython ipykernel pandoc
    - pip install -q sphinx sphinx_rtd_theme recommonmark nbsphinx
    - sphinx-build docs public
  dependencies:
    - build
  artifacts:
    paths:
      - public

# === Deploy ===

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    # Conda configure
    - case "${PACKAGE_VERSION}" in
      *dev*)
      anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u ${CI_PROJECT_NAMESPACE} --label dev --force
      ;;
      *)
      anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/linux-64/*.tar.bz2 -u ${CI_PROJECT_NAMESPACE}
      ;;
      esac
  only:
    - master
  except:
    - triggers
