default:
  image: condaforge/linux-anvil-cos7-x86_64:latest

stages:
  - build
  - test
  - deploy

# cache:
#   paths:
#     - .conda_packages

# === Variables ===

variables:
  PACKAGE_VERSION: 0.1.3

.configure:
  before_script:
    # Cargo
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    # Conda environment variables
    - export CONDA_PKGS_DIRS="${CI_PROJECT_DIR}/.conda_packages"
    # Make conda cache and bld folders
    - mkdir -p "${CI_PROJECT_DIR}/conda-bld" "${CONDA_PKGS_DIRS}"
    # Conda configure
    - |
      cat <<EOF > ~/.condarc
      channel_priority: true
      channels:
        - ostrokach-forge
        - conda-forge
        - defaults
      EOF
    - conda update -yq conda

# === Build ===

build:
  stage: build
  extends:
    - .configure
  script:
    - conda build "${CI_PROJECT_DIR}/.conda" --output-folder "${CI_PROJECT_DIR}/conda-bld"
  artifacts:
    paths:
      - conda-bld

# === Test ===

test:
  stage: test
  extends:
    - .configure
  dependencies:
    - build
  script:
    # Create conda environment for testing
    - conda update -yq conda
    - conda create -n test -q -c file://${CI_PROJECT_DIR}/conda-bld --strict-channel-priority
      "python=3.9" ${CI_PROJECT_NAME} pytest || true
    - source activate test
    # Run tests
    - python -m pytest -c setup.cfg --color=yes "tests/"

# === Pages ===

pages:
  stage: test
  extends:
    - .configure
  dependencies:
    - build
  script:
    # Conda install
    - cp -r $CI_PROJECT_DIR/conda-bld/* /opt/conda/conda-bld/
    - conda index /opt/conda/conda-bld/
    - conda install -yq --use-local "python=$PYTHON_VERSION" $CI_PROJECT_NAME
    # Build docs
    - conda install -yq nbconvert ipython ipykernel pandoc
    - pip install -q sphinx sphinx_rtd_theme recommonmark nbsphinx
    - sphinx-build docs public
  dependencies:
    - build
  artifacts:
    paths:
      - public

# === Deploy ===

deploy:
  stage: deploy
  extends:
    - .configure
  script:
    - anaconda -t $ANACONDA_TOKEN upload $CI_PROJECT_DIR/conda-bld/*/*.tar.bz2 -u ostrokach-forge --no-progress
  dependencies:
    - build
  only:
    - tags
