[package]
name = "biodata-parsers"
version = "0.1.0"
authors = ["ostrokach <ostrokach@gmail.com>"]
description = "Scripts for parsing UniParc XML files downloaded from the Uniprot website into CSV files."
homepage = "https://ostrokach.github.io/uniparc_xml_parser"
documentation = "https://ostrokach.github.io/uniparc_xml_parser"
repository = "https://github.com/ostrokach/uniparc_xml_parser"
readme = "README.md"
license = "MIT"
exclude = [
    "tests/*",
]

[dependencies]
xml-rs = "0.3"

